[package]
name = "bitcup-store"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
redb = { workspace = true }
fd-lock = { workspace = true }
tempfile = "3"

[dev-dependencies]
