[package]
name = "bitcup-api"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
bitcup-core = { workspace = true }
bitcup-store = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3"
